# Generated by Django 3.1.1 on 2020-10-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FundingProgramTbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.TextField(max_length=1000)),
                ('about_program', models.TextField(max_length=5000)),
                ('who_can_apply', models.TextField(max_length=5000)),
                ('deadline', models.TextField(max_length=5000)),
                ('how_to_apply', models.TextField(max_length=5000)),
                ('link', models.TextField(max_length=5000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
